import type { Food } from "@/lib/foodDatabase";
import { getFilteredRecommendations, POSITIVE_LEARNING_EVENT, readPositiveLearningState, recordRecommendationView, recordSwapActivity, SwapRecommendation } from "@/lib/positiveLearning";
import { CheckCircle2, ChevronDown, Leaf, Lightbulb, ShieldCheck } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

function SwapCard({ food, recommendation }: { food: Food; recommendation: SwapRecommendation }) {
  const [viewed, setViewed] = useState(false);
  const [tried, setTried] = useState(false);
  const [loggedNewMeal, setLoggedNewMeal] = useState(false);
  const viewOption = () => { setViewed(true); recordRecommendationView(recommendation.id); };
  const recordTried = () => { recordSwapActivity({ originalMealId: food.id, originalMealName: food.name, suggestedOption: recommendation.alternative, loggedNewMeal }); setTried(true); toast.success("Your swap activity was recorded privately."); };
  return <article className="rounded-2xl border border-[#d9e5d0] bg-white p-4"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#e4f0d8] text-[#2b6b43]"><Lightbulb className="size-5" aria-hidden="true" /></div><div><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-[#5f895e]">Explore another option</p><h3 className="font-display mt-1 text-2xl tracking-[-0.045em] text-[#244c36]">{recommendation.alternative}</h3></div></div><p className="mt-3 rounded-xl bg-[#f5f7ef] px-3 py-2 text-xs font-bold text-[#52705b]"><span className="font-extrabold">Starting from: </span>{recommendation.original}</p><p className="mt-4 text-sm leading-6 text-[#516d5a]"><span className="font-extrabold">Why it may help: </span>{recommendation.explanation}</p><p className="mt-3 rounded-xl bg-[#fff8e9] p-3 text-xs leading-5 text-[#765e32]"><span className="font-extrabold">Important to know: </span>{recommendation.limitation}</p><button type="button" onClick={viewOption} className="mt-4 min-h-11 w-full rounded-xl border border-[#b9d8b4] bg-[#edf6e7] px-4 text-sm font-extrabold text-[#286142] active:scale-95 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2c7049]">View this option</button>{viewed && <div className="mt-3 rounded-xl bg-[#f5f7ef] p-3"><label className="flex min-h-10 items-center gap-3 text-sm font-extrabold text-[#416047]"><input aria-label={`I logged ${recommendation.alternative} in Daily History`} type="checkbox" checked={loggedNewMeal} onChange={(event) => setLoggedNewMeal(event.target.checked)} className="size-5 accent-[#216442]" />I logged this option in Daily History</label><button type="button" onClick={recordTried} disabled={tried} className="mt-3 min-h-11 w-full rounded-xl bg-[#216442] px-4 text-sm font-extrabold text-white shadow-[0_3px_0_#143e2a] active:scale-95 disabled:cursor-default disabled:bg-[#7ea184] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2c7049]">{tried ? "Swap activity recorded" : "I tried this option"}</button><p className="mt-2 text-xs leading-5 text-[#697d6d]">Viewing this idea does not mean you completed the swap.</p></div>}</article>;
}

export default function SustainableSwapSection({ food }: { food: Food }) {
  const [state, setState] = useState(() => readPositiveLearningState());
  useEffect(() => { const refresh = () => setState(readPositiveLearningState()); window.addEventListener(POSITIVE_LEARNING_EVENT, refresh); return () => window.removeEventListener(POSITIVE_LEARNING_EVENT, refresh); }, []);
  const recommendations = useMemo(() => getFilteredRecommendations(food.id, state.preferences), [food.id, state.preferences]);
  if (!state.settings.recommendationsEnabled) return null;
  return <section className="mt-6 rounded-[1.75rem] border border-[#dce8d1] bg-[#fffdf5] p-5 shadow-[0_10px_24px_rgba(36,79,54,0.08)] sm:p-6" aria-labelledby="swap-title"><div className="flex items-start gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-[#e5f0d9] text-[#276540] shadow-[0_4px_0_#bdd2a9]"><Leaf className="size-5" aria-hidden="true" /></div><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-[#5a865c]">Optional ideas</p><h2 id="swap-title" className="font-display mt-1 text-3xl tracking-[-0.05em] text-[#173f2e]">Sustainable Food Swaps</h2><p className="mt-2 text-sm leading-6 text-[#5d7465]">Explore another option if it works for you. This is private and never changes your meal score.</p></div></div><details className="mt-5 rounded-2xl border border-[#d9e5d0] bg-[#f6f8f2]"><summary className="flex min-h-12 cursor-pointer items-center gap-2 px-4 text-sm font-extrabold text-[#315f42] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2c7049]"><ChevronDown className="size-4" aria-hidden="true" />Why this swap?</summary><div className="border-t border-[#dbe7d6] px-4 pb-4 pt-3 text-sm leading-6 text-[#54705c]">Food footprint estimates can change because of ingredients, serving size, sourcing, production method, recipe, and cooking energy. <span className="font-extrabold">More data is needed for a reliable comparison.</span></div></details>{recommendations.length ? <div className="mt-4 space-y-4">{recommendations.map((recommendation) => <SwapCard key={recommendation.id} food={food} recommendation={recommendation} />)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-[#c9dcc4] bg-[#f6f8f2] p-5 text-center"><ShieldCheck className="mx-auto size-7 text-[#5b8a61]" aria-hidden="true" /><p className="mt-3 font-extrabold text-[#365942]">No swap option is shown for these preferences.</p><p className="mt-2 text-sm leading-6 text-[#66806d]">Your allergy, safety, or ingredient settings are respected.</p></div>}<p className="mt-4 flex gap-2 text-xs leading-5 text-[#66806d]"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#5b8a61]" aria-hidden="true" />The original meal and this idea are shown without a made up carbon saving.</p></section>;
}
